sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t ad/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ad/react-test npm test

after_success:
  - docker build -t ad/multi-client ./client
  - docker build -t ad/multi-nginx ./nginx
  - docker build -t ad/multi-server ./server
  - docker build -t ad/multi-worker ./worker

  # log in to the docker CLI
  - echo $DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # after success build we need to push into docker hub
  - docker push ad/multi-client
  - docker push ad/multi-nginx
  - docker push ad/multi-server
  - docker push ad/multi-worker
